version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sta_go
      MYSQL_DATABASE: blog
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: blog-redis
    command: redis-server --requirepass sta_go
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blog-network

  # Kafka消息队列
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: blog-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - blog-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: blog-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - blog-network

  # API网关
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: blog-api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - wallet-service
      - comment-service
    networks:
      - blog-network

  # 用户服务
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    container_name: blog-user-service
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - blog-network

  # 钱包服务
  wallet-service:
    build:
      context: .
      dockerfile: services/wallet-service/Dockerfile
    container_name: blog-wallet-service
    ports:
      - "8002:8002"
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - blog-network

  # 评论服务
  comment-service:
    build:
      context: .
      dockerfile: services/comment-service/Dockerfile
    container_name: blog-comment-service
    ports:
      - "8003:8003"
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - blog-network

volumes:
  mysql_data:
  redis_data:

networks:
  blog-network:
    driver: bridge
